var i;
var mensaje=new Array();

mensaje.push("<h2>1) La PC disminuyo su rendimiento <br></h2><h1>- Posibles causas: Este es el problema mas habitual entre los usuarios. Pueden haber muchas razones que expliquen una baja en el rendimiento de la PC. La mas comun es la presencia de datos fragmentados, presencia de spyware, registro corrupto, y programas innecesarios. <br>- La solucion: Chequear los programas que tenemos instalados y desinstalar los que no usas, borrar los archivos innecesarios, y ganar velocidad y rendimiento, ya sea desfragmentando el disco, o bien añadiendo memoria a la maquina. </h1>");
mensaje.push("<h2>2) Aparecen pantallas de error, los programas se tildan y se cierran <br></h2><h1>- Posibles causas: El posible que nuestra PC tenga spyware o programas espia, y que esa sea la causa de que los programas no respondan y se deban finalizar.Tambien esta la de que el programa no funciona bien. Otra es que haya archivos de Windows necesarios para ejecutarlos y estan corruptos. Otra causa puede ser la falta de memoria RAM. <br>- La solucion: Si bien alcanzaria con actualizar un programa anti-spyware, las causas pueden venir de otro lado, como drivers mal instalados. Podrias fijarte re-instalando el programa que funciona mal. Si el problema es con windows seria recomendable no formatear sino REPARAR WINDOWS , si notamos que el problema puede venir de la memoria RAM, se le puede agregar mayor memoria virtual a la PC y asi optimizar su rendimiento. </h1>");
mensaje.push("<h2>3) La computadora se reinicia automaticamente o se apaga <br></h2><h1>- Posibles causas: Pueden ser dos. La presencia de un -gusano- (un tipo de virus), o alguna obstruccion ( basura, mala coneccion ) dentro del gabinete o el cooler. Esto ultimo sucede cuando la PC no puede refrescarse: antes de recalentarse, sencillamente se apaga. <br>- La solucion: Si se trata de un virus, correr los antivirus correspondientes. Si el problema es una obstruccion, una buena forma de evitarlo es mantener el interior del gabinete y el cooler limpios, tener la cpu en un lugar ventilado, y evitar su exposicion al humo. Si el problema persiste, el problema puede ser la fuente de la PC, por lo que habria que chequear si esta funciona correctamente o si esta bien conectada. </h1>");
mensaje.push("<h2>4) Ruidos extraños y vibraciones provenientes del gabinete <br></h2><h1>- Posibles causas: Algun componente del gabinete o hardware esta fallando, ya sea el cooler, la fuente, cables mal conectados, o placas mal colocadas. Aqui las causas pueden ser multiples. <br>- La solucion: Abrir el gabinete y chequear que este todo bien conectado. Si no encontramos ninguna anormalidad en el gabinete fijar si hay algun hardware que no funcione bien, buscar los drivers, si es muy complicado lo mas conveniente es llamar al servicio tecnico. </h1>");
mensaje.push("<h2>5) La pagina de inicio o el buscador se cambio solo <br></h2><h1>- Posibles causas: Es probable que hayamos sido victimas del -high-jacking-. Esto quiere decir que tenemos un spyware instalado en nuestra PC, que pudo haber provenido tanto de un archivo descargado y ejecutado tanto como de una red socia o lun mail. <br>- La solucion: Es probable que el spyware haya instalado un -java script- en el navegador para cambiar las opciones personales. Corriendo algun programa de diagnostico, se puede evitar la llamada al servicio tecnico. </h1>");

for(i=0 ;i<=4;i++)
{

document.write(mensaje[i])


}